GPUS: (0,)
WORKERS: 24
PRINT_FREQ: 10
USE_GPU: True
LOCAL: False

DATASET:
  CLASS: animal
  NAME: 'whaleshark'
  MAX_ROT: 180
  SCALE_FACTOR: [0.8, 1.2]
  HOR_FLIP_PROB: 0.5
  VERT_FLIP_PROB: 0.5
  TEST_SET: test2020
  TRAIN_SET: train2020

MODEL:
  CORE_NAME: 'efficientnet-b4'
  IMSIZE:
  - 224
  - 224

TRAIN:
  END_EPOCH: 100
  LR: 0.0001

TEST:
  MODEL_FILE: 'wbia_orientation/output/whaleshark_6_efficientnet_coords_v0/best.pth'
  HFLIP: True
  VFLIP: True
  PLOT_ROTATED: True
  PLOT_ERRORS: True
  PLOT_ROTATED_PREDS_ONLY: True
